### PR TITLE
Implement ActionBuffer to speed up runtime indexing

### PR DESCRIPTION
**Pull request by confususs**
At [HelloLily](https://hellolily.com/) we're (finally!) working on the stuff @HansAdema worked on a year ago.

I asked him if I could update [his PR](https://github.com/sabricot/django-elasticsearch-dsl/pull/73) to resolve merge conflicts. As he was working on other stuff he said that I could make my own PR which includes his changes. So, here it is! 

The original descriptions still apply, I just fixed the merge conflicts.

### CODE REVIEW

**Comment by abdelwahebmoalla** [comment]
Is this branch gonna be merged any time soon ?

**Comment by confususs** [comment]
Don't merge this yet. I recently discovered that this stores all the objects of a certain class into a list before adding them to ES. This could cause memory problems, so I'll fix this in a few weeks.

**Comment by crazyscientist** [comment]
Hi everyone,

first I'd like to apologize for not being familiar with the code base. The `ActionBuffer` implementation looks to me like it can't be used as a drop-in replacement for the `RealTimeSignalProcessor`. This leads me to the question what would I have to change to take full advantage of it?

**Comment by confususs** [comment]
The RealTimeSignalProcessor makes sure that the appropriate events are triggered after a save/delete to update the relevant elasticsearch index. With this PR, if you now save a model in django, all ES changes (including related models) are stored in the ActionBuffer before they are processed in bulk, where this previously happened one-by-one.

One of the things that you can do to take full advantage of the ActionBuffer, is to sync all your models with elasticsearch at once by calling a management command django-elasticsearch-dsl introduces. (i.e. `search_index --rebuild [-f] [--models [app[.model] app[.model] ...]]`)

The only problem (that happens with *really* large datasets) is that you should have enough memory to buffer a lot of fields. The buffer should empty every once in a while to avoid memory overload, using a paginator of some sort. So if you are able to spend time in changing anything, change that part.

**Comment by crazyscientist** [comment]
@confususs thank you for the clarification. It seems I was using your implementation correctly for the runtime tests with the backend of my Django app. For my usecase it did not perform much better compared to the current release.

If I can spare some time, I can try looking into it. I think I saw another PR for pagination.

**Comment by nicholasamorim** [comment]
Has this work ever been implemented in another PR?

**Comment by qcoumes** [comment]
Any update on this PR ? I'm facing the same problem, I can provide some help if needed.

**Comment by confususs** [comment]
Unfortunately I don't see myself working on this anytime soon, so I'll close this PR. I don't know if something similar has been implemented in the meantime, but if there is still a need for this change feel free to fork it.

**Pull request closed without merging**
