### PR TITLE
Class-based view for Django

### PR DESCRIPTION
**Pull request by crazyscientist**
For one of my projects I wanted to use the search results from elasticsearch in an analogous way like query results. Therefore I have written a view class that can be used to easily provide a view for listing results, e.g.:

```python
class MyView(FormMixin, ElasticListView):
    model = Issue
    document = IssueDocument
    paginate_by = 25
    form_class = SearchForm

    def _get_queryset(self):
        # Build your ES query here
       ...

    ...

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)
```
This is just a demo to give you the idea of the usage.

If you like the idea, I will put some effort in writing documentation and tests for this :)

### CODE REVIEW

**Comment by abdelwahebmoalla** [comment]
@crazyscientist I like the idea please provide more examples

**Comment by safwanrahman** [comment]
Can you add some documentations?

**Comment by safwanrahman** [comment]
This looks really interesting. I will work on this to make it compatable with new version. @crazyscientist I am sorry for the delay, are you still interested to work on this?

**Comment by crazyscientist** [comment]
I am also sorry :laughing: Somewhere between 2019 and now we discovered that a setup with Elasticsearch did not fulfill the expectation of users to search data in real-time. So we do the search in the database again; with some strong query optimization.

**Comment by safwanrahman** [comment]
@crazyscientist Cool, I can understand. Can you share some thoughts about the database search? Which database, how do you optimize, what is the response time?

**Comment by crazyscientist** [comment]
@safwanrahman In our app we now also use Datatables, which is fed by an API based on DRF. Our optimizations for the two most common use cases are implemented in a subclass of `rest_framework_datatables.django_filters.backends.DatatablesFilterBackend`. The idea was basically, to identify the use case based on the search term with a few quick queries and then construct a query with subqueries for that particular use case.
With a Postgres DB a user usually gets results in less than 4 seconds; I know, it's not great, but nobody complains :joy:

**Pull request closed without merging**
