### PR TITLE
Allow custom routing and index prefixing during bulk indexing using aliases and index templates.

### PR DESCRIPTION
**Pull request by martyzz1**

### CODE REVIEW

**Comment by safwanrahman** [comment]
Thanks for the PR. Can you add some documentation for this?

**Comment by martyzz1** [comment]
I've pushed up some more changes. this now seems to work fine allowing creation of indexes and aliases.

What I'm not sure about is how to deal with the read from index...   I'm in a microservices environment where my rread and write are on separate services so its not a problem for me to specify the write index as "thing" and on the other service specify the read index as "thing_r_alias"

**Comment by martyzz1** [comment]
With regards to documentation The new management command es_reindex.py Makes use of all the features.. Not sure where to document it all?

**Comment by safwanrahman** [comment]
@alexgarel Can you help him to put the documentations?

**Comment by timo-piirmann** [comment]
👍  for this effort. Looks exactly what I need to replace my custom scripts in the system.

**Comment by violuke** [comment]
Will this also resolve? #75 If so, is there anything holding this up other than documentation, I'd be happy to help out as #75 would be really helpful for us?

**Comment by martyzz1** [comment]
I think it would...

**Comment by safwanrahman** [comment]
@martyzz1 I think you can document it in the management command page. Let me know if you need any help documenting it.

**Comment by safwanrahman** [comment]
Looks like it is implemented with  #358

**Pull request closed without merging**
