### PR TITLE
Filter populate command

### PR DESCRIPTION
**Pull request by sajadbahar**
Here is implement of populate with filter,

you could use Django filter phrase like `{field_name}__gte`, ...

### CODE REVIEW

**Comment by herrnici** [comment]
Any progress on fixing and merging this? I find this an important feature.

**Comment by safwanrahman** [comment]
@herrnici Can you explain your usecase?

**Comment by herrnici** [comment]
@safwanrahman A large table of versioned data (division into multiple models is not an option), where only current data is needed for search, and therefore only current data should be indexed. Of course this would also work by

- filtering every search (wastes space, slight runtime impact)
- manually deleting the majority of the data from the index after every build (inconvenient, temporarily wastes space), or
- changing the default manager to only include partial data (has impacts on other components).

But I feel needing only a subset of data isn't that uncommon a use case.

**Comment by alexgarel** [comment]
@herrnici, given your usecase, why don't you simply override `get_queryset` in you `Document`  class ?

**Comment by herrnici** [comment]
Good point, that should cover all cases. No idea why I didn't think of that.
In that case this PR is really somewhat redundant. Thank you and sorry for the ping.

**Pull request closed without merging**
