### PR TITLE
Added support for Elasticsearch 8

### PR DESCRIPTION
**Pull request by oehrlein**
I've made changes so Elasticsearch 8 works with this package.

The big caveat here is that testing via GitHub actions fail, but they run without error locally. If anyone could help get that fixed, that would be greatly appreciated as I don't have much experience with Github actions.

### CODE REVIEW

**Comment by DarkAbhi** [comment]
> I've made changes so Elasticsearch 8 works with this package.
> 
> The big caveat here is that testing via GitHub actions fail, but they run without error locally. If anyone could help get that fixed, that would be greatly appreciated as I don't have much experience with Github actions.

The cause for the actions failing is because python2.7 support was removed from Actions some time around June.

**Comment by safwanrahman** [comment]
Thanks @oehrlein for the PR. I need to test it locally with ES 8. Have you tested it locally?

**Comment by oehrlein** [comment]
@DarkAbhi All the other Python versions are failing as well. I've toyed around with it for a bit and has to do with the security settings that come with Elasticsearch 8, namely the security certificate.

Regarding Python 2.7 not being supported by GitHub actions, I did see that as well, but didn't want to remove that in this PR since I think it'd be more fitting to remove it separately.

**Comment by oehrlein** [comment]
@safwanrahman I have! All the tests pass for me.

**Comment by tevariou** [comment]
@oehrlein @safwanrahman would it be possible to open a new branch for 7.x and merge this pr on main with https://github.com/oehrlein/django-elasticsearch-dsl/pull/6 ?

**Comment by safwanrahman** [comment]
There are some fixes that need to be done in Github CI to pass the tests in CI. I think this PR is ready to go!
Thanks a lot @oehrlein. r+ from my end.

**Pull request merged**
