### PR TITLE
Backwards compatibility with Elasticsearch 6.x

### LINKED ISSUE #241: Support multiple versions of Elasticsearch
At the moment, we have very undesirable situation, where we can't use most recent version of this library with [still supported versions of Elasticsearch](https://www.elastic.co/support/eol). Think of 6.x and 7.x branches. If one uses Django 2.2 in combination with Elasticsearch 6.x, he can't simply migrate to Django 3.0 due to errors. 

I suggest to move towards Django way (or GitFlow way) - maintain Elasticsearch (6.x, 7.x) branches and update them both upon need.

Alternatively, a simple ``compat`` module could be created to deal with breaking changes. 

It shouldn't be overdone, though. For instance, once, Elasticseach 8.0 is released, 6.x maintenance could be stopped.

### PR DESCRIPTION
**Pull request by barseghyanartur**
Backwards compatibility with Elasticsearch 6.x (which is still widely used by many-many devs). With this all features available in current master are automatically available to 6.x with very minor code changes.

Closes #241

### CODE REVIEW

**Comment by safwanrahman** [comment]
I had similar plan, but I would like to maintain different version for that. like 6.x for that to comply with elasticsearch-dsl version. What do you think?

**Comment by barseghyanartur** [comment]
Since code does not require much changes (they're really minimal), it would only make things complicated. Besides, from my experience, both [django-elasticsearch-dsl-drf](https://github.com/barseghyanartur/django-elasticsearch-dsl-drf) and [graphene-elastic](https://github.com/barseghyanartur/graphene-elastic) work just fine this way.

**Comment by safwanrahman** [comment]
@barseghyanartur I have changed the base to `6.x` also made a commit for appropiate changes. Can you cherry-pick 23af5ee7238b3bf4daf57f9b150ddcb9d8c6741e and push to this repository? If it is not possible to do this, Can you mark `Allow edits by maintainers` in the left side of the PR so I can push directly to your branch.

**Comment by barseghyanartur** [comment]
> @barseghyanartur I have changed the base to `6.x` also made a commit for appropiate changes. Can you cherry-pick [23af5ee](https://github.com/django-es/django-elasticsearch-dsl/commit/23af5ee7238b3bf4daf57f9b150ddcb9d8c6741e) and push to this repository? If it is not possible to do this, Can you mark `Allow edits by maintainers` in the left side of the PR so I can push directly to your branch.

It was already checked (the checkbox allow edits by maintainers, but I unchecked and checked it again, in case it should have triggered some action).

**Comment by pencil** [comment]
@safwanrahman Any chance to get this merged?

**Comment by safwanrahman** [comment]
Seems like I still can not push to the repository 😞! Maybe some bug in Github!
BTW, merging it and pushing my change later.

**Comment by safwanrahman** [comment]
@pencil Released on Pypi!
https://pypi.org/project/django-elasticsearch-dsl/6.5.0/

**Comment by safwanrahman** [comment]
Thanks @barseghyanartur 😎🤩

**Pull request merged**
